apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9113'
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-conf
              readOnly: true
          resources:
            requests:
              cpu: "0.25"
              memory: "256Mi"
            limits:
              memory: "512Mi"
              cpu: "1"
        - name: adapter
          image: nginx/nginx-prometheus-exporter
          args: ["-nginx.scrape-uri", "http://localhost/nginx_status"]
            #args:
            #- '-nginx.scrape-uri=http://localhost/nginx_status'
          ports:
            - containerPort: 9113
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9113
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9113
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: "0.25"
              memory: "256Mi"
            limits:
              memory: "512Mi"
              cpu: "1"
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1
          maxSurge: 1
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-config
            items:
              - key: default.conf
                path: default.conf

---


apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-metrics
spec:
  selector:
    app: nginx
  ports:
    - name: ngmon
      protocol: TCP
      port: 8080
      targetPort: 9113
  type: ClusterIP


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen       80;
      server_name  localhost;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
        }

      location /nginx_status {
        stub_status on;
        access_log off;
        allow 127.0.0.1;
        deny all;
      }
    }

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  minReplicas: 3
  maxReplicas: 50
  targetCPUUtilizationPercentage: 50
