apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-monitor
spec:
  selector:
    matchLabels:
      app: nginx-metrics
  endpoints:
  - interval: 5s
    path: /metrics
    port: ngmon
    targetPort: 9113
